# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2bd5ca0121a8871973ebc4e72d7955bd92ae8487ff5646656e7305abfa2d407a9064583d150cda431645d87b856f0191412d7a7a339f0bf02e71a21996f6032b

test:
  secret_key_base: 9b55947532778e836da9f632c3a05c83e4c65ceadaae7cfef32eb3e903369b98e578cae53ab60d7ad77af1fe9ed462db486e6f3bf78c5df4bc9f1d8eded28464

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
